apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-8ylf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-8ylf
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-8ylf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-8ylf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-8ylf
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jhzo-tenant/rhtap-demo-app/hacbs-test-project-8ylf@sha256:aa349e07ddef511407eaa7761714f8baa44c1816ebc5f80b943201364d1738ba
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
